version: "3"
networks:
  uetbccode:
services:
  azure-tunnel:
    image: kroniak/ssh-client
    restart: "always"
    networks:
      - uetbccode
    command:
      - /bin/bash
      - -c
      - |
        ssh -oStrictHostKeyChecking=no -p 22222 -R code:80:vs:3000 uetbc.xyz
  vs:
    image: gitpod/openvscode-server
    restart: "always"
    networks:
      - uetbccode
    environment:
      - DOCKER_HOST=tcp://172.16.10.47:2375
    volumes:
      - ~/workspace:/home/workspace:cached