version: "3"
services:
  azure-tunnel:
    image: kroniak/ssh-client
    restart: "always"
    command:
      - /bin/bash
      - -c
      - |
        ssh -oStrictHostKeyChecking=no -p 22222 -R code:80:vs:3000 uetbc.xyz
  vs:
    image: gitpod/openvscode-server
    restart: "always"
    volumes:
      - ~/workspace:/home/workspace:cached