version: "3"
services:
  azure-tunnel:
    image: kroniak/ssh-client
    restart: "always"
    command:
      - /bin/bash
      - -c
      - |
        ssh -oStrictHostKeyChecking=no -p 22222 -R 34545:10.20.11.1:22 uetbc.xyz
 