version: '3.7'

services:
#  letsencrypt:
#    image: adferrand/dnsrobocert:latest
#    container_name: letsencrypt-dns
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./letsencrypt:/etc/letsencrypt
#      - ./le-config.yml:/etc/dnsrobocert/config.yml
#    restart: always
  sish:
    image: sonntuet1997/sish:latest
    container_name: sish
#    depends_on:
#      - letsencrypt
    volumes:
#      - ./letsencrypt:/etc/letsencrypt
      - ./pubkeys:/pubkeys
      - ./keys:/keys
      - ./ssl:/ssl
    command: |
      --ssh-address=:22222
      --http-address=:80
      --https-address=:443
      --https=true
      --https-certificate-directory=/ssl
      --authentication-keys-directory=/pubkeys
      --private-key-location=/keys/ssh_key
      --bind-random-ports=false
      --tcp-aliases
      --banned-aliases=api
      --bind-any-host=false
      --bind-random-subdomains=false
      --redirect-root=true
      --domain=dev.nftal.io
      --force-requested-aliases
      --force-requested-ports
      --ping-client-interval=1m
      --ping-client-timeout=2m
      --idle-connection-timeout=30m
      --force-requested-subdomains
      --https-ondemand-certificate=true
      --https-ondemand-certificate-accept-terms=true
      --https-ondemand-certificate-email=sonntuet1997@gmail.com
    network_mode: host
    restart: always
