version: '3.7'

services:
#  letsencrypt:
#    image: adferrand/dnsrobocert:latest
#    container_name: letsencrypt-dns
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./letsencrypt:/etc/letsencrypt
#      - ./le-config.yml:/etc/dnsrobocert/config.yml
#    restart: always
  sish:
    image: antoniomika/sish:latest
    container_name: sish
#    depends_on:
#      - letsencrypt
    volumes:
#      - ./letsencrypt:/etc/letsencrypt
      - ./pubkeys:/pubkeys
      - ./keys:/keys
      - ./ssl:/ssl
    command: |
      --ssh-address=:22222
      --http-address=localhost:9999
      --https-address=:10000
      --https=true
      --https-certificate-directory=/ssl
      --authentication-keys-directory=/pubkeys
      --private-key-location=/keys/ssh_key
      --bind-random-ports=false
      --tcp-aliases
      --banned-aliases=api
      --bind-any-host=false
      --bind-random-subdomains=false
      --domain=dev.nftal.io
    network_mode: host
    restart: always
