version: "3.3"
networks:
  dev:
    name: dev
services:
  server:
    #    deploy:
    #      resources:
    #        limits:
    #          memory: ${MEMORY_LIMIT}
    #        reservations:
    #          memory: ${MEMORY_RESERVATIONS}
    image: sonntuet1997/ai-assignment:latest
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    networks:
      - dev
    restart: always

  nginx:
    image: sonntuet1997/ai-assignment-proxy:latest
    ports:
      - 80:80
    environment:
      - API_URL=http://server:8000
      - UI_URL=http://nextjs:3000
    restart: "always"
    networks:
      - dev
  nextjs:
    image: sonntuet1997/ai-assignment-ui:latest
    networks:
      - dev
