version: "3"
networks:
  commento:
services:
  db:
    image: postgres:11.8
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: "always"
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    networks:
      - commento
  commento:
    image: registry.gitlab.com/commento/commento:latest
    environment:
      COMMENTO_ORIGIN: https://commento.uetbc.xyz
      COMMENTO_PORT: 80
      COMMENTO_POSTGRES: postgres://postgres:postgres@db:5432/commento?sslmode=disable
    restart: "always"
    depends_on:
      - db
    networks:
      - commento
  commento-tunnel:
    image: kroniak/ssh-client
    restart: "always"
    networks:
      - commento
    command:
      - /bin/bash
      - -c
      - |
        ssh -oStrictHostKeyChecking=no -p 22222 -R commento:80:commento:80 uetbc.xyz
volumes:
  postgres_data_volume: