version: "3"
networks:
  uetbccode:
services:
  ssh-tunnel:
    image: kroniak/ssh-client
    restart: "always"
    networks:
      - uetbccode
    command:
      - /bin/bash
      - -c
      - |
        ssh -oStrictHostKeyChecking=no -p 22222 -R 33333:vs:22 uetbc.xyz
  vs-tunnel:
    image: kroniak/ssh-client
    restart: "always"
    networks:
      - uetbccode
    command:
      - /bin/bash
      - -c
      - |
        ssh -oStrictHostKeyChecking=no -p 22222 -R stable-coin:80:vs:3000 uetbc.xyz
        
  vs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RELEASE_TAG: openvscode-server-v1.63.2
    restart: "always"
    networks:
      - uetbccode
    # ports:
      # - 30000:3000
    environment:
      - CONNECTION_SECRET=stablecoin-uet
      - DOCKER_HOST=tcp://10.20.11.1:2375
      - SRC_ROOT=/home/sv1/stable-coin/workspace/
    volumes:
      - ~/stable-coin/workspace:/home/workspace:cached