version: '3.7'

services:
  android-builder:
    image: sonntuet1997/android-builder:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AZP_URL=https://10.8.0.6
      - AZP_TOKEN=fscwwyal7c5amoohbexupcsmrpt4m4uew7uqoib42oto2amkwzpq
      - AZP_AGENT_NAME=android-builder4
      - AZP_POOL=AndroidBuilder
    restart: always
