version: "3.8"
networks:
  vm:
    name: vm

services:
  hoang-anh-vm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RELEASE_TAG=openvscode-server-v1.67.0
        - GO_VERSION=go1.18.2.linux-amd64
    restart: "always"
    networks:
      - vm
    ports:
       - "14008:22"
       - "14009:3000"
    runtime: sysbox-runc
    command:
      - /bin/bash
      - -c
      - |
        /home/admin/openvscode-server-v1.67.0-linux-x64/bin/openvscode-server --host 0.0.0.0 --connection-token=9yuQfOLbYH
    volumes:
      - ~/vm/hoang-anh:/home/admin/codes
