version: "3.8"
networks:
  vm:
    name: vm

services:
  vu-vm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RELEASE_TAG=openvscode-server-v1.67.0
        - GO_VERSION=go1.18.2.linux-amd64
    restart: "always"
    networks:
      - vm
    ports:
       - "14002:22"
       - "14003:3000"
    runtime: sysbox-runc
    volumes:
      - ~/vm/vu:/home/admin/codes
      - ./vu-token.txt:/home/admin/.secret
