version: "3.8"
networks:
  vm:
    name: vm

services:
  do-thanh-dat-vm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RELEASE_TAG=openvscode-server-v1.67.0
        - GO_VERSION=go1.18.2.linux-amd64
    restart: "always"
    networks:
      - vm
    ports:
       - "14006:22"
       - "14007:3000"
    runtime: sysbox-runc
    volumes:
      - ~/vm/dothanhdat:/home/admin/codes
      - ./do-thanh-dat-token.txt:/home/admin/.secret
