version: "3.8"
networks:
  vm:
    name: vm

services:
  hoang-anh-vm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RELEASE_TAG=openvscode-server-v1.67.0
        - GO_VERSION=go1.18.2.linux-amd64
    restart: "always"
    networks:
      - vm
    ports:
       - "14008:22"
       - "14009:3000"
    runtime: sysbox-runc
    volumes:
      - ./hoang-anh-token.txt:/home/admin/.secret
      - ~/vm/hoang-anh:/home/admin/codes
