version: "3"
services:
  azure-tunnel:
    image: kroniak/ssh-client
    restart: "always"
    command:
      - /bin/bash
      - -c
      - |
        ssh -oStrictHostKeyChecking=no -p 22222 -R 8080:192.168.168.2:8080 dev.nftal.io
