version: "3"
services:
  azure-tunnel:
    image: kroniak/ssh-client
    restart: "always"
    command:
      - /bin/bash
      - -c
      - |
        ssh -oStrictHostKeyChecking=no -p 22222 -R 8080:172.16.10.49:80 uetbc.xyz
 