version: "3"
services:
  portainer-tunnel:
    image: kroniak/ssh-client
    restart: "always"
    command:
      - /bin/bash
      - -c
      - |
        ssh -oStrictHostKeyChecking=no -p 22222 -R portainer:443:10.20.11.1:9443 uetbc.xyz auto-close=true
 