version: "3"
services:
  rancher-tunnel:
    image: kroniak/ssh-client
    restart: "always"
    command:
      - /bin/bash
      - -c
      - |
        ssh -oStrictHostKeyChecking=no -p 22222 -R harbor:80:10.8.0.10:30002 uetbc.xyz auto-close=true
 